version: '3.5'

services:

##################### 使用ollama部署大模型 #####################

# OLLAMA_HOST       The host:port to bind to (default "127.0.0.1:11434")
# OLLAMA_ORIGINS    A comma separated list of allowed origins.
# OLLAMA_MODELS     The path to the models directory (default is "~/.ollama/models")

  ollama:
    restart: always
    container_name: ollama
    image: ollama/ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_MODELS=/data/models
      - OLLAMA_DEBUG=1
    volumes:
      - ./models/:/data/models
      - ./run_ollama.sh:/run_ollama.sh
    # 命令启动 serve
    entrypoint: /run_ollama.sh

## https://github.com/Chanzhaoyu/chatgpt-web
  open-webui:
        ports:
            - 8192:8080
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./open-webui:/app/backend/data
        container_name: open-webui
        restart: always
        image: ghcr.io/open-webui/open-webui:main


